SUPPORTED_TEACHING_STEP = "decision"
SUPPORTED_EVIDENCE_LAYER = "whatWorks"
SUPPORTED_THRESHOLD_QUESTION = "breakEvenRent"
SUPPORTED_EVALUATE_DEAL_REQUEST_INTENT = "evaluateDeal"
SUPPORTED_EVALUATE_DEAL_INPUT_INTENT = "selectedDefaultInput"
SUPPORTED_EVALUATE_DEAL_WORKBOOK_SOURCE_INTENT = "resolvedWorkbookAssumptions"
SUPPORTED_EVALUATE_DEAL_RECEIPT_ACTION_ID = "evaluateDeal"
SUPPORTED_EVALUATE_DEAL_RECEIPT_SOURCE = "verifiedJavaScriptEvaluateRentalDeal"
SUPPORTED_EVALUATE_DEAL_RECEIPT_TRACE_IDS = (
    "cashFlow",
    "repairDrivers",
    "tenYear",
    "whatWorks",
)
SUPPORTED_SOLVER_RECEIPT_ACTION_ID = "askThresholdQuestion"
SUPPORTED_SOLVER_RECEIPT_SOURCE = "verifiedJavaScriptSolveThresholdQuestion"
SUPPORTED_SOLVER_RECEIPT_QUESTION_ID = SUPPORTED_THRESHOLD_QUESTION
SUPPORTED_SOLVER_RECEIPT_VARIABLE = "rent"
SUPPORTED_SOLVER_RECEIPT_METRIC = "monthlyCashFlow"
SUPPORTED_SOLVER_RECEIPT_TARGET_VALUE = 0
SUPPORTED_SOLVER_RECEIPT_TRACE_IDS = SUPPORTED_EVALUATE_DEAL_RECEIPT_TRACE_IDS
SUPPORTED_SOLVED_VALUE_APPLY_ACTION_ID = "applySolvedInput"
SUPPORTED_SOLVED_VALUE_APPLY_SOURCE = "verifiedJavaScriptApplySolvedInputCommand"
SUPPORTED_SOLVED_VALUE_APPLY_VARIABLE = SUPPORTED_SOLVER_RECEIPT_VARIABLE
SUPPORTED_SOLVED_VALUE_APPLY_INPUT_FIELD = "actualGrossMonthlyRent"
SUPPORTED_SOLVED_VALUE_APPLY_RESULT_STATUS = "ok"


SELECTED_SCENARIO = {
    "teaching_step": SUPPORTED_TEACHING_STEP,
    "evidence_layer": SUPPORTED_EVIDENCE_LAYER,
    "threshold_question": SUPPORTED_THRESHOLD_QUESTION,
    "evaluate_deal_request_intent": SUPPORTED_EVALUATE_DEAL_REQUEST_INTENT,
    "evaluate_deal_input_intent": SUPPORTED_EVALUATE_DEAL_INPUT_INTENT,
    "evaluate_deal_workbook_source_intent": (
        SUPPORTED_EVALUATE_DEAL_WORKBOOK_SOURCE_INTENT
    ),
    "evaluate_deal_receipt_action_id": SUPPORTED_EVALUATE_DEAL_RECEIPT_ACTION_ID,
    "evaluate_deal_receipt_source": SUPPORTED_EVALUATE_DEAL_RECEIPT_SOURCE,
    "evaluate_deal_receipt_trace_ids": SUPPORTED_EVALUATE_DEAL_RECEIPT_TRACE_IDS,
    "solver_receipt_action_id": SUPPORTED_SOLVER_RECEIPT_ACTION_ID,
    "solver_receipt_source": SUPPORTED_SOLVER_RECEIPT_SOURCE,
    "solver_receipt_question_id": SUPPORTED_SOLVER_RECEIPT_QUESTION_ID,
    "solver_receipt_variable": SUPPORTED_SOLVER_RECEIPT_VARIABLE,
    "solver_receipt_metric": SUPPORTED_SOLVER_RECEIPT_METRIC,
    "solver_receipt_target_value": SUPPORTED_SOLVER_RECEIPT_TARGET_VALUE,
    "solver_receipt_trace_ids": SUPPORTED_SOLVER_RECEIPT_TRACE_IDS,
    "solved_value_apply_action_id": SUPPORTED_SOLVED_VALUE_APPLY_ACTION_ID,
    "solved_value_apply_source": SUPPORTED_SOLVED_VALUE_APPLY_SOURCE,
    "solved_value_apply_variable": SUPPORTED_SOLVED_VALUE_APPLY_VARIABLE,
    "solved_value_apply_input_field": SUPPORTED_SOLVED_VALUE_APPLY_INPUT_FIELD,
    "solved_value_apply_result_status": (
        SUPPORTED_SOLVED_VALUE_APPLY_RESULT_STATUS
    ),
}
